# GoReleaser configuration for kbVault
# See: https://goreleaser.com

version: 2
# Project metadata:
project_name: kbvault
# Environment variables:
env:
  - GO111MODULE=on

git:
  tag_sort: -version:refname

builds:
  - id: kbvault
    main: ./cmd/kbvault
    binary: kbvault
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags: -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

# universal_binaries for macOS
universal_binaries:
  - id: kbvault_universal
    replace: true
    name_template: kbvault

before:
  hooks:
    - go mod tidy
    - ./scripts/generate-completions.sh

archives:
  - id: default
    format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG*
      - completions/*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

# Changelog
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Enhancements"
      regexp: "^.*enhance[(\\w)]*:+.*$"
      order: 2
    - title: "Performance Improvements"
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 3
    - title: "Refactoring"
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 4
    - title: "Other"
      order: 999

# Software Bill of Materials (SBOM)
sboms:
  - artifacts: archive
  - id: source
    artifacts: source

release:
  github:
    owner: madstone-tech
    name: mdstn-kb-mcp
  draft: false
  prerelease: auto
  mode: replace

  # Header for the release body.
  header: |
    ## kbVault {{.Version}} - Knowledge Management CLI

    Welcome to this new release of kbVault! 🎉

    This release brings new features and improvements to your knowledge management workflow.

    ### Installation

    **Using Homebrew (macOS & Linux):**
    ```bash
    brew tap madstone-tech/tap
    brew install kbvault
    ```

    **Using Go:**
    ```bash
    go install github.com/madstone-tech/mdstn-kb-mcp/cmd/kbvault@{{.Version}}
    ```

    **Binary Download:**
    Download the appropriate binary for your platform from the assets below.

    ### Verification

    ```bash
    kbvault --version
    ```

  # Footer for the release body.
  footer: |
    ## What's Changed

    This release includes the following changes from the previous version.

    **Full Changelog**: https://github.com/madstone-tech/mdstn-kb-mcp/compare/{{.PreviousTag}}...{{.Tag}}

    ---

    **Checksums**: Verify downloaded binaries with `sha256sum -c checksums.txt`


# Homebrew (macOS package manager)
brews:
  - repository:
      owner: madstone-tech
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/madstone-tech/mdstn-kb-mcp
    description: "Knowledge Base Vault CLI - A command-line tool for managing and searching your knowledge base"
    license: MIT
    test: |
      system "#{bin}/kbvault --version"
    install: |
      bin.install "kbvault"

      # Generate and install shell completions
       bash_completion.install "completions/kbvault.bash" => "kbvault" if File.exist?("completions/kbvault.bash")
      zsh_completion.install "completions/_kbvault" if File.exist?("completions/_kbvault")
      fish_completion.install "completions/kbvault.fish" if File.exist?("completions/kbvault.fish")

# Announce releases
announce:
  # Skip announcement for now
  skip: true
