name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "🐛 [Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form to help us understand and reproduce the issue.

  - type: checkboxes
    id: search
    attributes:
      label: Search existing issues
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      value: |
        - OS: [e.g. macOS 13.0, Ubuntu 22.04, Windows 11]
        - Go version: [e.g. 1.23.0]
        - kbVault version: [e.g. v1.0.0]
        - Installation method: [e.g. binary, Docker, source]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please copy and paste any relevant log output
      render: shell
      placeholder: |
        # Add logs here
        # Use --verbose flag for more detailed logs

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please share your configuration (remove any sensitive information)
      render: toml
      placeholder: |
        # Your kbvault.toml configuration (sanitized)

  - type: checkboxes
    id: terms
    attributes:
      label: Additional Information
      options:
        - label: I can reproduce this issue consistently
        - label: This issue occurs with the latest version
        - label: I'm willing to help test a fix